# Generated by Django 5.1.2 on 2025-02-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='candidateaccess',
            name='status',
            field=models.CharField(choices=[('not_read', 'Не просмотрено'), ('access', 'Документы приняты'), ('not_access', 'Документы не были посланы')], default='not_read', max_length=100),
        ),
    ]
