services:
  backend:
    build: kvspb_time_ticket/
    ports:
      - "80:80"

    volumes:
      - db:/app/data/database/

  bot:
    env_file: "bot.env"
    build: kvspb_hr_bot_main/
    depends_on:
      - backend

volumes:
  db: