services:
  backend:
    build: kvspb_time_ticket/
    ports:
      - "8000:8000"

    volumes:
      - db:/app/

  bot:
    env_file: "bot.env"
    build: kvspb_hr_bot_main/
    depends_on:
      - backend

volumes:
  db: